title: "<XantarDev />"
description: "Comunidad Técnica"
logo: "/favicon.svg"
social_image: "/assets/img/social-default.svg"
url: "https://xantardev.github.io"
baseurl: "/xantardev.org"
lang: "gl-ES"
timezone: "Europe/Madrid"
permalink: "/:title/"
paginate: 5
paginate_path: "/page:num/"

sponsor_sections:
  - title: "Alojamiento"
    sponsors:
      - name: "dinahosting"
        url: "https://dinahosting.com"
        logo: "/wp-content/uploads/2018/05/dinahostingLogo.png"
  - title: "Patrocinio 2025"
    sponsors:
      - name: "Mews"
        url: "https://www.mews.com/"
        logo: "/wp-content/uploads/2025/09/image-1-1024x322.png"
  - title: "Patrocinio 2022/2023"
    sponsors:
      - name: "Plain Concepts"
        url: "https://www.plainconcepts.com/"
        logo: "/wp-content/uploads/2022/04/plain-concepts-01-main-logo-RGB_s.png"
        alt: "Patrocinador Diamante del Aniversario IV+II"
  - title: "Colaboramos con"
    sponsors:
      - name: "commit"
        url: "https://commit-conf.com"
        logo: "/wp-content/uploads/2018/06/commit.png"

exclude:
  - Dockerfile
  - docker-compose.yml
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
